name: bookshelf
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_animated_button: ^2.0.3
  flutter_rating: ^2.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.3 #TODO: Now:  shared_preferences 2.2.3 (2.3.1 available)
                                          #shared_preferences_android 2.2.4 (2.3.1 available)
                                          #shared_preferences_foundation 2.4.0 (2.5.2 available)
                                          #shared_preferences_linux 2.3.2 (2.4.1 available)
                                          #shared_preferences_platform_interface 2.4.0 (2.4.1 available)
                                          #shared_preferences_web 2.3.0 (2.4.2 available)
                                          #shared_preferences_windows 2.3.2 (2.4.1 available)
                              # Should only need for android + ios
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets: 
  - assets/icons/add.svg
  - assets/icons/library.svg
  - assets/icons/profile.svg

  fonts:
  - family: StratfordRegular
    fonts:
      - asset: assets/fonts/StratfordRegular.ttf
        weight: 400
